base_url = "https://miguelpimentel.do/zola-guava/"
title = "Zola Guava"
description = "Guava is a Zola theme."

compile_sass = true
generate_feed = true
minify_html = true
build_search_index = false
taxonomies = [{ name = "categories" }, { name = "tags" }]

[markdown]
highlight_code = true
# highlight_theme = "zenburn"

[extra]
blog_title = "Guava"
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_relative_posts = "Relative Posts"
label_next = "Next"
label_previous = "Previous"
label_page = "Page"
label_of = "of"
label_minutes = "minutes"

og_image = "https://raw.githubusercontent.com/semanticdata/public-test/main/PNG/myfinalform.png" # Image that will appear on social media
og_alt_image = "My final form."
og_site_name = "Zola Guava"
keywords = "guava, theme, rust, zola"

educational_use = "knowledge share" # OPTIONAL
copyright_year = "2023"             # OPTIONAL

sidebar = [
    { name = "Links", urls = [
        { name = "Blog", url = "https://miguelpimentel.do" },
        { name = "Digital Garden", url = "https://forgetfulnotes.com" },
        { name = "Source", url = "https://github.com/semanticdata/zola-guava" },
    ] },
    { name = "Social", urls = [
        { name = "GitHub", url = "https://github.com/semanticdata" },
        { name = "Instagram", url = "https://instagram.com/miguelapv" },
        { name = "Linkedin", url = "https://linkedin.com/miguelpimentel29" },
    ] },
]
